### ISSUE TITLE
Custom Home Assistant URL breaks stuff

### ISSUE THREAD

**Issue by lindhe** [outadoc/home-slide-android#362] opened 2021-01-09 20:58 UTC
**Describe the bug**
For my installation of Home Assistant, I use a FQDN with proper HTTPS (e.g., `https://home.example.com`) setup instead of just using the defacto `http://192.168.0.2:8123` alternative. I would expect this to work also for Home Slide, but instead I get an error. Sounds to me like a parser is making a bad assumption regarding the format of the "Home Assistant URL" string...

**To Reproduce**
1. Settings
2. Click on "Home Assistant URL"
3. Set it to https://home.example.com
4. Save and go back to the main screen
5. It tries to reload, but fails with the message "Something happened. Failed to connect to localhost/127.0.0.1:80"

**Expected behavior**
It should try to connect to my Home Assistant server.

**Screenshots**
![photo_2021-01-09_21-52-12](https://user-images.githubusercontent.com/7773090/104108472-2227ca00-52c5-11eb-98a4-193be6ce80f9.jpg)

**Smartphone (please complete the following information):**
 - Device: Samsung Galaxy S8
 - OS: Android 9
 - App Version 1.5.11

**Comment by outadoc** [comment] 2021-02-09 18:20
Hi, thanks for the feedback!

The error message is actually caused by a questionably-well-written HTTP interceptor that tries both of the base URLs. 

However what's shown on the error isn't actually what's been called by the app. I'll keep this opened because that message really could be improved 🙂

**Comment by outadoc** [comment] 2021-02-21 13:20
This should be fixed by #367. The messages should now reflect the actual errors that occurred.

**Closed as completed by outadoc** 2021-02-21 13:20 UTC
Labels: improvement
